name: Release

on:
  push:
    tags:
    - v*

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    
    - name: Get dependencies
      run: GO111MODULE=on go mod download

    - name: patch deps
      run: |
        patch -R -p0 vendor/github.com/abbot/go-http-auth/digest.go -i digest.go.patch
        patch -N -p0 vendor/github.com/abbot/go-http-auth/digest.go -i digest.go.patch
    
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    
    - name: docker hub login
      env:
        HUB_PASSWORD: ${{ secrets.HUB_PASSWORD }}
      run: docker login -u egeneralov -p ${HUB_PASSWORD}
    
    - name: docker build+push
      run: docker buildx build -t ${GITHUB_REPOSITORY}:$(echo $GITHUB_REF | awk -F \/ '{print $3}') --platform linux/amd64,linux/arm64,linux/arm/v7 --output "type=image,push=true" .
    
    - name: docker hub logout
      run: docker logout
    
    - name: prepare helm package
      run: |
        export TAG=$(echo $GITHUB_REF | awk -F \/ '{print $3}')
        sed -i "s/version: .*/version: $TAG/g" .helm/digest-auth-proxy/Chart.yaml
        sed -i "s/  tag: .*/  tag: $TAG/g" .helm/digest-auth-proxy/values.yaml
        helm package .helm/digest-auth-proxy
    
    - name: save in actions
      uses: actions/upload-artifact@v1.0.0
      with:
        name: helm-chart
        path: digest-auth-proxy-*.tgz
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: digest-auth-proxy-*.tgz
        asset_name: helm-chart
        asset_content_type: application/x-gzip
